# 使用sklearn实现关键词提取+文档余弦相似度计算

## 测试一

In [1]:
contents = [
    '我 是 中国 人。',
    '你 是 美国 人。',
    '他 叫 什么 名字？',
    '她 是 做咩啊？'
];

from sklearn.feature_extraction.text import CountVectorizer

#Convert a collection of text documents to a matrix of token counts
countVectorizer = CountVectorizer()
#Learn the vocabulary dictionary and return  term-document  matrix.
textVector = countVectorizer.fit_transform(contents)

In [2]:
textVector 

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [3]:
textVector.todense()#看上面的输出应该是 稀疏矩阵，这里是将其转换成了 稠密矩阵，方便人为查看
#行为 document 列为term

matrix([[1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0]], dtype=int64)

In [4]:
countVectorizer.vocabulary_#输出所有的 terms和对应的下标（应该是代码里会将词映射到数字），至于为什么是两个字母及以上 看下面

{'中国': 0, '什么': 1, '做咩啊': 2, '名字': 3, '美国': 4}

In [5]:
countVectorizer.get_feature_names()

['中国', '什么', '做咩啊', '名字', '美国']

In [6]:
countVectorizer#可以从 token_pattern='(?u)\\b\\w\\w+\\b' 看到初始设定是 提取至少两个字母的词（正则表达式）

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

## 测试二

In [7]:
countVectorizer1 = CountVectorizer(
    min_df=0, 
    token_pattern=r"\b\w+\b"#现在指定 匹配至少有一个字母的term
)
textVector1 = countVectorizer1.fit_transform(contents);

In [8]:
textVector1.todense()

matrix([[1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
        [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1],
        [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [9]:
countVectorizer1.vocabulary_

{'中国': 0,
 '人': 1,
 '什么': 2,
 '他': 3,
 '你': 4,
 '做咩啊': 5,
 '叫': 6,
 '名字': 7,
 '她': 8,
 '我': 9,
 '是': 10,
 '美国': 11}

In [10]:
countVectorizer1.get_feature_names()

['中国', '人', '什么', '他', '你', '做咩啊', '叫', '名字', '她', '我', '是', '美国']

## 测试三：TF-IDF

In [11]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
contents = [
    '我 是 中国 人。',
    '你 是 美国 人。',
    '他 叫 什么 名字？',
    '她 是 做咩啊？'
]

countVectorizer = CountVectorizer()
textVector = countVectorizer.fit_transform(contents)

transformer = TfidfTransformer()
tfidf = transformer.fit_transform(textVector)#输入term-document  matrix，转换为稠密矩阵即是 行为 document 列为term

tfidf.toarray()

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ]])

In [12]:
# help(TfidfTransformer)

In [13]:
import pandas
TFIDFDataFrame = pandas.DataFrame(tfidf.toarray())
TFIDFDataFrame.columns = countVectorizer.get_feature_names()
TFIDFDataFrame

中国        什么  做咩啊        名字   美国
0  1.0  0.000000  0.0  0.000000  0.0
1  0.0  0.000000  0.0  0.000000  1.0
2  0.0  0.707107  0.0  0.707107  0.0
3  0.0  0.000000  1.0  0.000000  0.0

In [14]:
import numpy
#对每一行进行排序，得到排序的下标
TFIDFSorted = numpy.argsort(tfidf.toarray(), axis=1)
TFIDFSorted

array([[1, 2, 3, 4, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 1, 3],
       [0, 1, 3, 4, 2]], dtype=int64)

In [15]:
TFIDFDataFrame.columns # Index

Index(['中国', '什么', '做咩啊', '名字', '美国'], dtype='object')

In [16]:
TFIDFDataFrame.columns.values # array

array(['中国', '什么', '做咩啊', '名字', '美国'], dtype=object)

In [17]:
TFIDFDataFrame.columns[TFIDFSorted]

Index([['什么', '做咩啊', '名字', '美国', '中国'], ['中国', '什么', '做咩啊', '名字', '美国'],
       ['中国', '做咩啊', '美国', '什么', '名字'], ['中国', '什么', '名字', '美国', '做咩啊']],
      dtype='object')

In [18]:
TFIDFDataFrame.columns[TFIDFSorted].values #pandas.Index.values return the underlying data as an ndarray

array([['什么', '做咩啊', '名字', '美国', '中国'],
       ['中国', '什么', '做咩啊', '名字', '美国'],
       ['中国', '做咩啊', '美国', '什么', '名字'],
       ['中国', '什么', '名字', '美国', '做咩啊']], dtype=object)

In [19]:
'''if-idf矩阵中 矩阵元素值越大 则对应元素的重要性也就更加大，因此可选取值最大的前 K 个作为对应document的 K个关键词'''
import numpy
TFIDFSorted = numpy.argsort(tfidf.toarray(), axis=1)[:, -2:]
print("\n对于每条句子，得到2个关键词（从左到右重要性递增）：")
TFIDFDataFrame.columns[TFIDFSorted].values


对于每条句子，得到2个关键词（从左到右重要性递增）：


array([['美国', '中国'],
       ['名字', '美国'],
       ['什么', '名字'],
       ['美国', '做咩啊']], dtype=object)

## 测试4：实际应用

### 4.1.得到数据

In [20]:
# -*- coding: utf-8 -*-
import os
import os.path
import codecs
import pandas
import re
import jieba
import numpy

filePaths = []
fileContents = []

'''注：SogouC.mini是搜狗提供的文本分类现成语料库（有10个领域的语料，每个领域有10个样本，共有100条数据）'''
dictPath=os.path.join(os.getcwd(),'SogouC.mini\\Sample')#语料库样本所在路径

for root, dirs, files in os.walk(dictPath):
    for name in files:
        filePath = os.path.join(root, name)
        filePaths.append(filePath)
        with open(filePath, 'r', encoding='utf-8') as f:
            fileContent = f.read()
            fileContents.append(fileContent)

corpos = pandas.DataFrame({
    'filePath': filePaths, 
    'fileContent': fileContents
})

zhPattern = re.compile(u'[\u4e00-\u9fa5]+')#匹配中文的正则表达式

segments = []
filePaths = []
for index, row in corpos.iterrows():
    segments = []
    filePath = row['filePath']
    fileContent = row['fileContent']
    segs = jieba.cut(fileContent) #使用jieba进行分词   
    for seg in segs:
        if zhPattern.search(seg):#只保留中文的分词结果
            segments.append(seg)
    filePaths.append(filePath)
    row['fileContent'] = " ".join(segments)#以空格分隔分词后的结果，以适应sklearn

corpos

Building prefix dict from the default dictionary ...
Loading model from cache D:\TEMP\jieba.cache
Loading model cost 1.060 seconds.
Prefix dict has been built succesfully.


fileContent  \
0   在 政府部门 明确 表示 汽车 投资 过热 产能 过剩 的 背景 下 日前 新飞 集团 却 ...   
1   近日 国内 一项 调查 结果表明 的 人 喜欢 开 轿车 的 人 喜欢 开 面包车 的 人 ...   
2   消息 传来 强制 缴纳 元 年 的 保费 最高 却 只 赔 万 随着 月 日 大限 的 临近...   
3   编辑 观点 价格 相差 两万元 我会 选 花冠 几天 前 曾 有 机会 聆听 时尚 杂志社 ...   
4   全球性 汽车品牌 应 如何 在 中国 做 售后服务 中国经济时报 记者 就 这 一 话题 曾...   
5   沙特 石油大臣 称 油价 到 年 将 会 稳定 沙特阿拉伯 石油 和 矿产资源 大臣 纳伊米...   
6   月 日 开摩 的 为生 的 岁 河北 邯郸 人 袁 小宝 因 拒绝 北京市 丰台区 城管 和...   
7   韩元 升值 现代 汽车 遭遇 定价 尴尬 韩国现代 汽车 似乎 进入 了 公司 发展史 上 ...   
8   刚刚 过去 的 五一 长假 如果 问 谁 是 将 全部 身心 都 投入 黄金周 最 放松 的...   
9   昔日 富豪 骗贷 多万 疯狂 购买 辆 豪华轿车 短短 个 月 内 获得 多万元 贷款 疯狂...   
10  本报记者 陈雪频 实习 记者 唐翔 发自 上海 一家 刚刚 成立 两年 的 网络 支付 公司...   
11  焦点 个股 苏宁 电器 该股 早市 涨停 开盘 其后 虽 在 获利盘 的 抛 压下 略有 回...   
12  智威汤逊 全球 大众传媒 依然 是 品牌 传播 的 好 选择 本报记者 康健 发自 上海 想...   
13  新华网 上海 月 日电 中国石化集团 上海 工程 有限公司 最近 与 中石化 第二 建设 公...   
14  根据 艾瑞 市场 咨询 有限公司 发布 的 年 中国 网上支付 研究 报告 中国 网上支付 ...   
15  本报讯 记者 李英辉 已经 退出 北京 市场 两年 多 的 车贷险 业务 重现 市场 记者 ...   
16  本报 北京 月 日讯 记者 潘跃 今天 从 中国红十字会总会 举办 的 博爱 论坛 上 获悉...   
17  设想 一下 如果 某 家 银行 花 了 大 力气 进行 品牌 建设 可 顾客 每每 面对 的...   
18  如果 你 周围 的 不少 人 都 晋升 了 那 就 该 好好 反省 自己 了 看看 以下 种...   
19  本报讯 记者 段志敏 中国移动 北京地区 手机 资费 刚刚 下调 零售 终端 迅速 作出反应...   
20  本报讯 记者 王京 联想 近期 几乎 全系列 笔记本电脑 降价 促销 最高 降幅 达到 美元...   
21  本报讯 全球 最大 个人电脑 制造商 戴尔公司 日 说 由于 市场竞争 激烈 以及 定价 策...   
22  本报讯 记者 陆一波 售价 万港元 的 文渊阁 四库全书 电子版 在 易趣网 上 竟 以 元...   
23  关键字 裁员 美国在线 呼叫 中心 标题 美国在线 计划 裁员 人 占 全球 员工 总数 时...   
24  本报讯 记者 马海邻 记者 昨天 得到 确切 消息 新浪 公司 今天 将 宣布 由 曹国伟 ...   
25  全国 个 入围 项目 北京 考古 项目 遗憾 落选 十大 考古 新 发现 揭晓 本报记者 黄...   
26  本报记者 陆琼琼 记者 昨日 从 新浪 获悉 汪延 已经 正式 辞去 一职 曹国伟 将 接替...   
27  新华社 电 美国宇航局 官员 近日 说 宇航局 已 决定 设立 一项 总 奖金 为 万美元 ...   
28  日前 据 联想 相关 负责人 表示 为了 纪念 新 联想 成立 一周年 联想 在 美国市场 ...   
29  科龙德 勤案 又 有 新进展 已有 多位 科龙 H股 股东 到 律师 处 咨询 登记 所涉 ...   
..                                                ...   
70  新华网 深圳 月 日电 记者 贾文军 全国 拳击 锦标赛 日 在 深圳市 龙岗 体育中心 拉...   
71  看 今天 两会 特别 报道 已经 开始 启动 两会 和 我们 每个 人 的 生活 息息相关 ...   
72  年 月 日 北京 香港 利苑 饮食 集团 在 京 开办 的 第一家 食府 北京 利苑 酒家 ...   
73  留守 人士 自我安慰 在 北京 过 春节 的 十 理由 年 月 日 来源 新华网 字号 大 ...   
74  大学生 小 袁 网上 投 简历 求职 一家 自称 设在 广东 的 跨国公司 分公司 很快 就...   
75  讲述 我 网上 求职 险遭 名企 骗局 年 月 日 大学生 小 袁 网上 投 简历 求职 一...   
76  大学生 求职 供求 不 匹配 凸显 年 大学 毕业生 求职 面临 的 最大 障碍 是 供求 ...   
77  大学生 小 袁 网上 投 简历 求职 一家 自称 设在 广东 的 跨国公司 分公司 很快 就...   
78  大学生 小 袁 网上 投 简历 求职 一家 自称 设在 广东 的 跨国公司 分公司 很快 就...   
79  位 网友 领到 免费 回家 机票 自从 与 搜狐 天益游 网站 合办 夺宝奇兵 的 活动 以...   
80  从 今天 的 影响 来看 年 创立 的 数字 炼金 馆 无疑 是 数独 兴起 历程 中 一个...   
81  由 文物出版社 出版 的 中国 大史记 传世 邮币 珍藏 日 在 故宫 太庙 举行 了 首发...   
82  杭州 时间 年 月 日 日 地址 杭州 华辰 国际饭店 四层 会议厅 杭州 平 海路 号 南...   
83  夜幕 下 的 太和 门 广场 月 日晚 时值 中国 传统 佳节 农历 八月 十五 中秋节 之...   
84  大长 今 调查 你 看 大长 今 吗 不看 赶上 就 看 正在 追着 看 看过 遍 大长 今...   
85  哀乐 中年 年 文华 影业公司 出品 哀乐 中年 原著 张爱玲 编剧 桑弧 导演 桑弧 片长...   
86  倾城 之恋 年 香港 邵氏 公司出品 倾城 之恋 到处 都 是 传奇 可 不见得 有 这么 ...   
87  红玫瑰 与 白玫瑰 年 第一 机构 有限公司 出品 红玫瑰 白玫瑰 也许 每 一个 男子 全...   
88  半生 缘 年 香港 东方 影业公司 出品 半生 缘 他 一旦 想起 曼桢 就 觉得 他 从来...   
89  金锁记 金锁记 根据 张爱玲 同名 小说 改编 张爱玲 名著 中 的 名著 继 大宅门 橘子...   
90  本报 北京 月 日电 董宾 高立英 报道 北空 某 导弹 团 今天 传出 喜讯 营 参谋长 ...   
91  张连军 熊言春 本报 特约 通讯员 韩光 张旭 航 主人公 小传 耿大勇 沈阳军区 某 装甲...   
92  周 维华 田宁 本报 特约 通讯员 侯国 荣 月 日 凌晨 一阵 急促 的 报警 铃声 骤然...   
93  本报 特约 通讯员 刘 一代 本报 特约记者 王永孝 阳春 时节 记者 来到 第二炮兵 指挥...   
94  台湾 布 导弹 威胁 闽江 口 文章 认为 台军 在 距离 大陆 沿海 公里 的 岛屿 部署...   
95  中新网 月 日电 据 共同社 报道 围绕 导弹 防御 系统 问题 日本 海上 自卫队 日 宣...   
96  猎鹰 展翅 中国 新型 高级 教练机 研制成功 猎鹰 的 首飞 成功 对于 完善 中国 初 ...   
97  猎鹰 试翼 我国 第三代 高级 教练机 开始 试飞 总 设计师 对 若干 问题 的 解答 崎...   
98  新华网 北京 月 日电 题 强军 兴军 的 科学 方略 科学 发展观 引领 人民军队 阔步前...   
99  以 禁止 女兵 穿 低腰裤 已有 名 女兵 因 违规 被 关禁闭 据 新华社 电 以军 日前...   

                                             filePath  
0   E:\Code\_githubRepositories\How-TO-Use-XXX\How...  
1   E:\Code\_githubRepositories\How-TO-Use-XXX\How...  
2   E:\Code\_githubRepositories\How-TO-Use-XXX\How...  
3   E:\Code\_githubRepositories\How-TO-Use-XXX\How...  
4   E:\Code\_githubRepositories\How-TO-Use-XXX\How...  
5   E:\Code\_githubRepositories\How-TO-Use-XXX\How...  
6   E:\Code\_githubRepositories\How-TO-Use-XXX\How...  
7   E:\Code\_githubRepositories\How-TO-Use-XXX\How...  
8  

### 4.2.1.使用sklearn tf-idf得到文档前五个关键词
jieba.analyse.extract_tags

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

stopwords = pandas.read_csv("StopwordsCN.txt", encoding='utf8')

countVectorizer = CountVectorizer(
    stop_words=list(stopwords['stopword'].values),
    min_df=0, token_pattern=r"\b\w+\b"
)
textVector = countVectorizer.fit_transform(corpos['fileContent'])

transformer = TfidfTransformer()
tfidf = transformer.fit_transform(textVector)

sort = numpy.argsort(tfidf.toarray(), axis=1)[:, -5:]#提取5个关键词
names = countVectorizer.get_feature_names();

keywords = pandas.Index(names)[sort].values

tagDF = pandas.DataFrame({
    'filePath':corpos.filePath, 
    'fileContent':corpos.fileContent, 
    'tag1':keywords[:, 0], 
    'tag2':keywords[:, 1], 
    'tag3':keywords[:, 2], 
    'tag4':keywords[:, 3], 
    'tag5':keywords[:, 4]
})
tagDF

fileContent  \
0   在 政府部门 明确 表示 汽车 投资 过热 产能 过剩 的 背景 下 日前 新飞 集团 却 ...   
1   近日 国内 一项 调查 结果表明 的 人 喜欢 开 轿车 的 人 喜欢 开 面包车 的 人 ...   
2   消息 传来 强制 缴纳 元 年 的 保费 最高 却 只 赔 万 随着 月 日 大限 的 临近...   
3   编辑 观点 价格 相差 两万元 我会 选 花冠 几天 前 曾 有 机会 聆听 时尚 杂志社 ...   
4   全球性 汽车品牌 应 如何 在 中国 做 售后服务 中国经济时报 记者 就 这 一 话题 曾...   
5   沙特 石油大臣 称 油价 到 年 将 会 稳定 沙特阿拉伯 石油 和 矿产资源 大臣 纳伊米...   
6   月 日 开摩 的 为生 的 岁 河北 邯郸 人 袁 小宝 因 拒绝 北京市 丰台区 城管 和...   
7   韩元 升值 现代 汽车 遭遇 定价 尴尬 韩国现代 汽车 似乎 进入 了 公司 发展史 上 ...   
8   刚刚 过去 的 五一 长假 如果 问 谁 是 将 全部 身心 都 投入 黄金周 最 放松 的...   
9   昔日 富豪 骗贷 多万 疯狂 购买 辆 豪华轿车 短短 个 月 内 获得 多万元 贷款 疯狂...   
10  本报记者 陈雪频 实习 记者 唐翔 发自 上海 一家 刚刚 成立 两年 的 网络 支付 公司...   
11  焦点 个股 苏宁 电器 该股 早市 涨停 开盘 其后 虽 在 获利盘 的 抛 压下 略有 回...   
12  智威汤逊 全球 大众传媒 依然 是 品牌 传播 的 好 选择 本报记者 康健 发自 上海 想...   
13  新华网 上海 月 日电 中国石化集团 上海 工程 有限公司 最近 与 中石化 第二 建设 公...   
14  根据 艾瑞 市场 咨询 有限公司 发布 的 年 中国 网上支付 研究 报告 中国 网上支付 ...   
15  本报讯 记者 李英辉 已经 退出 北京 市场 两年 多 的 车贷险 业务 重现 市场 记者 ...   
16  本报 北京 月 日讯 记者 潘跃 今天 从 中国红十字会总会 举办 的 博爱 论坛 上 获悉...   
17  设想 一下 如果 某 家 银行 花 了 大 力气 进行 品牌 建设 可 顾客 每每 面对 的...   
18  如果 你 周围 的 不少 人 都 晋升 了 那 就 该 好好 反省 自己 了 看看 以下 种...   
19  本报讯 记者 段志敏 中国移动 北京地区 手机 资费 刚刚 下调 零售 终端 迅速 作出反应...   
20  本报讯 记者 王京 联想 近期 几乎 全系列 笔记本电脑 降价 促销 最高 降幅 达到 美元...   
21  本报讯 全球 最大 个人电脑 制造商 戴尔公司 日 说 由于 市场竞争 激烈 以及 定价 策...   
22  本报讯 记者 陆一波 售价 万港元 的 文渊阁 四库全书 电子版 在 易趣网 上 竟 以 元...   
23  关键字 裁员 美国在线 呼叫 中心 标题 美国在线 计划 裁员 人 占 全球 员工 总数 时...   
24  本报讯 记者 马海邻 记者 昨天 得到 确切 消息 新浪 公司 今天 将 宣布 由 曹国伟 ...   
25  全国 个 入围 项目 北京 考古 项目 遗憾 落选 十大 考古 新 发现 揭晓 本报记者 黄...   
26  本报记者 陆琼琼 记者 昨日 从 新浪 获悉 汪延 已经 正式 辞去 一职 曹国伟 将 接替...   
27  新华社 电 美国宇航局 官员 近日 说 宇航局 已 决定 设立 一项 总 奖金 为 万美元 ...   
28  日前 据 联想 相关 负责人 表示 为了 纪念 新 联想 成立 一周年 联想 在 美国市场 ...   
29  科龙德 勤案 又 有 新进展 已有 多位 科龙 H股 股东 到 律师 处 咨询 登记 所涉 ...   
..                                                ...   
70  新华网 深圳 月 日电 记者 贾文军 全国 拳击 锦标赛 日 在 深圳市 龙岗 体育中心 拉...   
71  看 今天 两会 特别 报道 已经 开始 启动 两会 和 我们 每个 人 的 生活 息息相关 ...   
72  年 月 日 北京 香港 利苑 饮食 集团 在 京 开办 的 第一家 食府 北京 利苑 酒家 ...   
73  留守 人士 自我安慰 在 北京 过 春节 的 十 理由 年 月 日 来源 新华网 字号 大 ...   
74  大学生 小 袁 网上 投 简历 求职 一家 自称 设在 广东 的 跨国公司 分公司 很快 就...   
75  讲述 我 网上 求职 险遭 名企 骗局 年 月 日 大学生 小 袁 网上 投 简历 求职 一...   
76  大学生 求职 供求 不 匹配 凸显 年 大学 毕业生 求职 面临 的 最大 障碍 是 供求 ...   
77  大学生 小 袁 网上 投 简历 求职 一家 自称 设在 广东 的 跨国公司 分公司 很快 就...   
78  大学生 小 袁 网上 投 简历 求职 一家 自称 设在 广东 的 跨国公司 分公司 很快 就...   
79  位 网友 领到 免费 回家 机票 自从 与 搜狐 天益游 网站 合办 夺宝奇兵 的 活动 以...   
80  从 今天 的 影响 来看 年 创立 的 数字 炼金 馆 无疑 是 数独 兴起 历程 中 一个...   
81  由 文物出版社 出版 的 中国 大史记 传世 邮币 珍藏 日 在 故宫 太庙 举行 了 首发...   
82  杭州 时间 年 月 日 日 地址 杭州 华辰 国际饭店 四层 会议厅 杭州 平 海路 号 南...   
83  夜幕 下 的 太和 门 广场 月 日晚 时值 中国 传统 佳节 农历 八月 十五 中秋节 之...   
84  大长 今 调查 你 看 大长 今 吗 不看 赶上 就 看 正在 追着 看 看过 遍 大长 今...   
85  哀乐 中年 年 文华 影业公司 出品 哀乐 中年 原著 张爱玲 编剧 桑弧 导演 桑弧 片长...   
86  倾城 之恋 年 香港 邵氏 公司出品 倾城 之恋 到处 都 是 传奇 可 不见得 有 这么 ...   
87  红玫瑰 与 白玫瑰 年 第一 机构 有限公司 出品 红玫瑰 白玫瑰 也许 每 一个 男子 全...   
88  半生 缘 年 香港 东方 影业公司 出品 半生 缘 他 一旦 想起 曼桢 就 觉得 他 从来...   
89  金锁记 金锁记 根据 张爱玲 同名 小说 改编 张爱玲 名著 中 的 名著 继 大宅门 橘子...   
90  本报 北京 月 日电 董宾 高立英 报道 北空 某 导弹 团 今天 传出 喜讯 营 参谋长 ...   
91  张连军 熊言春 本报 特约 通讯员 韩光 张旭 航 主人公 小传 耿大勇 沈阳军区 某 装甲...   
92  周 维华 田宁 本报 特约 通讯员 侯国 荣 月 日 凌晨 一阵 急促 的 报警 铃声 骤然...   
93  本报 特约 通讯员 刘 一代 本报 特约记者 王永孝 阳春 时节 记者 来到 第二炮兵 指挥...   
94  台湾 布 导弹 威胁 闽江 口 文章 认为 台军 在 距离 大陆 沿海 公里 的 岛屿 部署...   
95  中新网 月 日电 据 共同社 报道 围绕 导弹 防御 系统 问题 日本 海上 自卫队 日 宣...   
96  猎鹰 展翅 中国 新型 高级 教练机 研制成功 猎鹰 的 首飞 成功 对于 完善 中国 初 ...   
97  猎鹰 试翼 我国 第三代 高级 教练机 开始 试飞 总 设计师 对 若干 问题 的 解答 崎...   
98  新华网 北京 月 日电 题 强军 兴军 的 科学 方略 科学 发展观 引领 人民军队 阔步前...   
99  以 禁止 女兵 穿 低腰裤 已有 名 女兵 因 违规 被 关禁闭 据 新华社 电 以军 日前...   

                                             filePath  tag1  tag2  tag3  tag4  \
0   E:\Code\_githubRepositories\How-TO-Use-XXX\How...    集团   冷藏车   奥克斯   汽车业   
1   E:\Code\_githubRepositories\How-TO-Use-XXX\How...    喜欢    轿车     开   多功能   
2   E:\Code\_githubRepositories\How-TO-Use-XXX\How...    三者     元    保费    强制   
3   E:\Code\_githubRepositories\How-TO-Use-XXX\How...    车身    动力   变速箱   发动机   
4   E:\Code\_githubRepositories\How-TO-Use-XXX\How...    服务    中国    保养    欧美   
5   E:\Code\_githubRe

### 4.2.2.使用sklearn计算文档余弦相似度

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

stopwords = pandas.read_csv("StopwordsCN.txt", encoding='utf8')

countVectorizer = CountVectorizer(
    stop_words=list(stopwords['stopword'].values),
    min_df=0, token_pattern=r"\b\w+\b"
)
textVector = countVectorizer.fit_transform(corpos['fileContent'])

from sklearn.metrics import pairwise_distances #余弦相似度计算函数

distance_matrix = pairwise_distances(
    textVector, 
    metric="cosine"
)

m = 1- pandas.DataFrame(distance_matrix)
m.columns = filePaths;
m.index = filePaths;

sort = numpy.argsort(distance_matrix, axis=1)[:, 1:6]#得到相似度最相近的5个文档

similarity5 = pandas.Index(filePaths)[sort].values

similarityDF = pandas.DataFrame({
    'filePath':corpos.filePath, 
    's1': similarity5[:, 0], 
    's2': similarity5[:, 1], 
    's3': similarity5[:, 2], 
    's4': similarity5[:, 3], 
    's5': similarity5[:, 4]
})
similarityDF

filePath  \
0   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
1   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
2   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
3   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
4   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
5   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
6   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
7   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
8   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
9   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
10  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
11  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
12  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
13  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
14  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
15  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
16  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
17  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
18  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
19  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
20  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
21  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
22  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
23  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
24  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
25  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
26  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
27  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
28  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
29  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
..                                                ...   
70  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
71  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
72  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
73  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
74  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
75  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
76  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
77  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
78  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
79  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
80  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
81  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
82  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
83  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
84  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
85  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
86  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
87  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
88  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
89  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
90  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
91  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
92  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
93  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
94  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
95  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
96  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
97  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
98  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
99  E:\Code\_githubRepositories\How-TO-Use-XXX\How...   

                                                   s1  \
0   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
1   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
2   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
3   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
4   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
5   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
6   E:\Code\_githubRepositories\How-TO-Use-XXX\How...   
7   E:\Code\_githubRepositories\How-TO-Use-XXX\How... 